added a containerd_prerequisites() function for configuring the required kernel modules and sysctl parameters

diff --git a/container-runtimes/containerd/install_containerd b/container-runtimes/containerd/install_containerd
--- a/container-runtimes/containerd/install_containerd
+++ b/container-runtimes/containerd/install_containerd
@@ -26,3 +26,23 @@ function main(){
     exit 1
   fi
 }
+
+function containerd_prerequisites(){
+  echo "$yellow Setting up containerd pre-requisites... $reset"
+  if [[ -e $working_directory/containerd.conf && -e $working_directory/99-kubernetes-cri.conf ]]
+  then
+    echo "$yellow Copying containerd.conf file to /etc/modules-load.d/... $reset"
+    cp "$working_directory"/containerd.conf /etc/modules-load.d/containerd.conf
+    echo "$yellow Ensuring that required kernel modules are loaded... $reset"
+    modprobe --verbose overlay
+    modprobe --verbose br_netfilter
+    echo "$yellow Copying 99-kubernetes-cri.conf file to /etc/sysctl.d/... $reset"
+    cp "$working_directory"/99-kubernetes-cri.conf /etc/sysctl.d/99-kubernetes-cri.conf
+    echo "$yellow Applying the required sysctl parameters... $reset"
+    sysctl --system
+    echo "$green Prerequisites completed. $reset"
+  else
+    error "$red Please ensure that the containerd.conf & 99-kubernetes-cri.conf files exists in the working directory first... $reset"
+    exit 1
+  fi
+}
